name:                RISCV-ISA-Spec
version:             0.1.0.0
github:              "rsnikhil/RISCV-ISA-Spec"
license:             BSD3
author:              "Rishiyur S. Nikhil"
maintainer:          "nikhil@bluespec.com"
copyright:           "2018 RISC-V Foundation, MIT, Rishiyur S. Nikhil, Bluespec, Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/rsnikhil/RISCV-ISA-Spec#readme>

dependencies:
- base >= 4.7 && < 5
- containers >=0.5 && <0.6
- bytestring >=0.10 && <0.11
- elf >=0.28

library:
  source-dirs: src

executables:
  RISCV-ISA-Spec-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RISCV-ISA-Spec

tests:
  RISCV-ISA-Spec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RISCV-ISA-Spec
