flags: {}
packages:
- .
extra-deps:
- QuickCheck-2.10.1
- aeson-1.4.2.0
- base-orphans-0.8
- exceptions-0.8.3
- free-5.1
- megaparsec-5.3.1
- primitive-0.6.4.0
- semigroupoids-5.3.2
- vector-algorithms-0.8.0.1
resolver: lts-12.26
