flags: {}
packages:
- .
- location:
    git: 'https://github.com/draperlaboratory/hope-policy-tool.git'
    commit: faea4a2c0031d5829c95d72d0ea54bc819ebf1f9
  extra-dep: true
- location:
    git: 'https://github.com/draperlaboratory/hope-policy-interpreter.git'
    commit: ed99fd4c4bb8634e3d0332a6b068cda9532e5e5e
    # was: 9b18ee7665ca4a1f641c9b1bcc6756b3c07b43d5
    # was: 91d709ee6ca7913664069893840500398eb8d836
    # was: 83fdc893a759da41273f98af6e1a8723156ef8e1
  extra-dep: true
  subdirs:
    - policy-eval

extra-deps:
  - elf-0.28

resolver: lts-9.21
